---
title: 'Hazard Ratios and 95% CI'
output:
  html_document:
    keep_md: yes
    toc: yes
  word_document:
    toc: no
date: 'Date: `r Sys.Date()`'
---

<!--  Set the working directory to the repository's base directory; this assumes the report is nested inside of two directories.-->
```{r, echo=F, message=F} 
# cat("Working directory: ", getwd())
library(knitr)
opts_knit$set(root.dir='../../')  #Don't combine this call with any other chunk -especially one that uses file paths.
```

<!-- Set the report-wide options, and point to the external code file. -->
```{r set_options, echo=F}
# cat("Working directory: ", getwd())
opts_chunk$set(
  results    = 'show', 
  comment    = NA, 
  tidy       = FALSE,
  fig.width  = 4, 
  fig.height = 4, 
  fig.path   = 'figure-png/'
)
# dpi = 400,
# out.width = "650px", #This affects only the markdown, not the underlying png file.  The height will be scaled appropriately.

echoChunks <- FALSE
options(width=120) #So the output is 50% wider than the default.
read_chunk("./reports/model-summaries/model-summaries.R") #This allows knitr to call chunks tagged in the underlying *.R file.
```

<!-- Load the sources.  Suppress the output when loading sources. --> 
```{r load-sources, echo=echoChunks, message=FALSE}
```

<!-- Load 'sourced' R files.  Suppress the output when loading packages. --> 
```{r load-packages, echo=echoChunks, message=FALSE}
```

<!-- Load any global functions and variables declared in the R file.  Suppress the output. --> 
```{r declare-globals, echo=echoChunks, results='show', message=FALSE}
```

<!-- Declare any global functions specific to a Rmd output.  Suppress the output. --> 
```{r, echo=echoChunks, message=FALSE}
#Put presentation-specific code in here.  It doesn't call a chunk in the codebehind file.
```

<!-- Load the datasets.   -->
```{r load-data, echo=echoChunks, results='show', message=FALSE, warning =FALSE}
```

```{r formatting-functions, echo=echoChunks, results='show', message=FALSE}
```

<!-- Tweak the datasets.   -->
```{r tweak-data, echo=echoChunks, results='hide', message=FALSE}
```

```{r prepare-odds-table, echo=echoChunks, results='hide', message=FALSE}
```


```{r print-dynamic-table-2, echo=echoChunks, message=TRUE, results='asis', eval=F}
```


```{r print-static-table-2, echo=echoChunks, message=TRUE, results='asis', eval=T}
```

```{r insert-odds-plots, echo=echoChunks, message=TRUE, results='show', eval=F}
```



# Session Information
For the sake of documentation and reproducibility, the current report was rendered on a system using the following software.

```{r session-info, echo=FALSE}
cat("Report rendered by", Sys.info()["user"], "at", strftime(Sys.time(), "%Y-%m-%d, %H:%M %z"))
sessionInfo()
```
